acl-org/acl-2023-miniconf

- .github/workflows/build.yml
Add CNAME to build so virtual site works
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/acl-org/acl-2023-miniconf/pull/10).
* __->__ #10
> Add CNAME to build so virtual site works

- acl_miniconf/data.py
- main.py
- templates/components.html
Fix missing date
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/acl-org/acl-2023-miniconf/pull/19).
* __->__ #19
> Fix missing date

- templates/base.html
Modify the header nav as per #17
> Modify header nav #17

- acl_miniconf/data.py
- acl_miniconf/import_acl2023.py
- templates/paper.html
> Add abstracts to paper, pass in display names for sessions

- acl_miniconf/import_acl2023.py
> Update the program

- acl_miniconf/rocketchat/cli.py
- configs/rocketchat/template.yaml
> Fix RC channel creation

- acl_miniconf/data.py
- acl_miniconf/import_acl2023.py
- acl_miniconf/rocketchat/cli.py
- templates/index.html
Fix RC and update program
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/acl-org/acl-2023-miniconf/pull/30).
* __->__ #30
> Fix RC and update program

- templates/plenary_session.html
Removes an element from a template showing debug information
> Removes a debug statement that made it into production by mistake.

- acl_miniconf/import_acl2023.py
> Update program with underline information, fix author names

- acl_miniconf/rocketchat/cli.py
- configs/rocketchat/template.yaml
- poetry.lock
- pyproject.toml
> Update scripts for tutorial channels

- acl_miniconf/data.py
- acl_miniconf/import_acl2023.py
- acl_miniconf/import_acl2023_workshop_papers.py
- acl_miniconf/rocketchat/cli.py
- configs/rocketchat/template.yaml
- data/acl_2023/data/workshop_papers.yaml
- data/acl_2023/data/workshops.yaml
> Add workshops

- templates/base.html
- templates/paper.html
> Make paper pages better by having tabs

- acl_miniconf/import_acl2023.py
> Fix issue with None in author names

- templates/index.html
> Remove notification

- acl_miniconf/import_acl2023.py
- templates/base.html
- templates/cal_head.html
- templates/index.html
- templates/schedule.html
> Fix timezones in non-paper program

- templates/components.html
- templates/workshop.html
The workshops.html and workshop.html pages needs a lot of refactoring due to the data model changes. I added this hotfix to display the names correctly on the main website now.
> fix workshop name displays

- acl_miniconf/load_site_data.py
- main.py
- templates/components.html
- templates/plenary_session.html
- templates/plenary_sessions.html
- templates/tutorial.html
This PR fixes two sets of issues:
* It modifies the Tutorials page which weren't showing information correctly
* It brings an updated Plenaries page with overall information for all plenary sessions
> Contributes a fix to the schedule fixing Tutorials and Plenaries

- templates/components.html
Removes an 'endfor' from a previous merge.
> Removes a dangling tag from a template

- main.py
Uncomment lines in freezer to serve the workshop pages.
> Serve individual workshop pages

- templates/components.html
Removes two extra `</div>` tags that were causing presentation issues for tutorials and plenaries.
> Fixes two unclosed `</div>` tags in a template

- acl_miniconf/data.py
- main.py
- templates/sessions.html
> Improve sessions display

- main.py
Uncomments and updates code for generating the static pages for plenary events.
> Brings back the code that generates pages for Plenary events.

- README.md
- acl_miniconf/data.py
- acl_miniconf/import_acl2023.py
- templates/index.html
> Fix issue with demo authors

- acl_miniconf/import_acl2023.py
- templates/base.html
> Fix industry and demo track assets/paper length

- templates/paper.html
> Add video link that pointers to underline

- templates/base.html
> Add header links back in

- acl_miniconf/import_acl2023.py
> Fix DI as social

- templates/index.html
> Improve landing page

- acl_miniconf/import_acl2023.py
> Program changes

- acl_miniconf/data.py
- acl_miniconf/import_acl2023.py
- acl_miniconf/import_acl2023_workshop_papers.py
- main.py
- static/css/main.css
- templates/paper.html
- templates/workshop.html
> Update main proceedings papers with their Anthology preview

- acl_miniconf/import_acl2023.py
> Add anthology links/pdfs to demo-industry papers

- acl_miniconf/data.py
- acl_miniconf/import_acl2023.py
- templates/tutorial.html
> Add anthology information for SRW papers and tutorials

- acl_miniconf/import_acl2023.py
> Fix findings papers links

- acl_miniconf/load_site_data.py
> Fix issue with day view calendar (mostly)

- acl_miniconf/load_site_data.py
- templates/plenary_session.html
This PR fixes two issues:
* It adds calendar links to Plenaries
* It solves a bug that happened when reloading the plenary page. This bug only happened on the dynamic site, but better to fix it now.
> Fixes calendar links for Plenaries and fixes a data bug

- acl_miniconf/data.py
- acl_miniconf/import_acl2023.py
- templates/sessions.html
> Make spotlights have sub-sessions

- static/css/main.css
- templates/sessions.html
> Make sub-tracks look nicer

- templates/base.html
- templates/index.html
> Add GatherTown link

- acl_miniconf/import_acl2023.py
> Switch to anthology main link

- .gitignore
- data/acl_2023/configs/config.yml
> Ignore local script, GA

- acl_miniconf/import_acl2023.py
- data/acl_2023/data/socials_data.json
- templates/socials.html
This PR changes the source of the social events, from the .xlsx file (which is slightly outdated) to a dedicated .json file.
> Updates information about social events from a different source

- data/acl_2023/data/socials_data.json
The LatinX social has just been confirmed. This PR adds it to the MC schedule.
> Adds a new social, "LatinX"

- acl_miniconf/data.py
- acl_miniconf/load_site_data.py
- templates/components.html
- templates/sessions.html
> Add deep linking

- templates/papers.html
- templates/papers_keyword_vis.html
> Re-enable keyword search
